version: "3"

tasks:
  run: once
  cf:types:
    run: once
    desc: Generate Cloudflare Worker binding types
    vars:
      D_TS: src/worker-configuration.d.ts
    cmds:
      - "bun wrangler types {{.D_TS}}"
    sources:
      - wrangler.toml
    generates:
      - "{{.D_TS}}"

  typecheck:
    run: once
    deps:
      - cf:types
    cmd: bun tsc

  lint:
    run: once
    deps:
      - cf:types
    cmd: bun oxlint --config ../../oxlint.config.ts src/

  check:
    deps:
      - lint
      - typecheck

  test:
    run: once
    deps:
      - test:unit
      - test:miniflare

  build:
    run: once
    desc: Build production web app
    cmds:
      - bun vite build
    sources:
      - ../../bun.lock
      - ./**/*.{ts,tsx}
      - exclude: node_modules/**/*
    generates:
      - .output/**/*

  test:miniflare:
    run: once
    deps:
      - build
    cmd: bun vitest run --config vitest.miniflare.config.ts
    sources:
      - ../../bun.lock
      - ./**/*.{ts,tsx}
      - exclude: node_modules/**/*

  test:unit:
    run: once
    cmd: bun test --path-ignore-patterns 'src/miniflare/**'

  dev:
    desc: Run Vite dev server
    cmds:
      - bun vite dev

  preview:
    desc: Preview production build
    cmds:
      - bun vite preview

  clean:
    cmds:
      - rm -rf .nitro/ .output/ dist/
