version: "3"

tasks:
  typecheck:
    cmds:
      - bun tsc

  compile:recurring:
    cmds:
      - bun spec/recurring.responsible.ts > spec/recurring.openapi.yaml

  compile:sheets:
    cmds:
      - bun spec/sheets.responsible.ts > spec/sheets.openapi.yaml

  compile:
    deps:
      - compile:recurring
      - compile:sheets

  generate:client:
    vars:
      OUT_DIR: ../../apps/web/gen/
    deps:
      - compile:recurring
    cmds:
      - rm -rf  {{.OUT_DIR}}
      - >-
        bun openapi-generator-cli generate
        -c config/ts-fetch.yaml
        -i spec/recurring.openapi.yaml
        -o {{.OUT_DIR}}

  generate:server-stubs:
    deps:
      - compile:recurring
    cmds:
      - bun openapi-generator-cli generate -c config/server-stubs.yaml

  typecheck:
    cmds:
      - bun tsc
