version: "3"

tasks:
  typecheck:
    cmds:
      - bun tsc

  compile:recurring:
    cmds:
      - bun spec/recurring.responsible.ts > spec/recurring.openapi.yaml

  compile:sheets:
    cmds:
      - bun spec/sheets.responsible.ts > spec/sheets.openapi.yaml

  compile:
    deps:
      - compile:recurring
      - compile:sheets

  generate:client:
    deps:
      - compile:recurring
    cmds:
      - bun openapi-generator-cli generate -c config/client.yaml

  generate:server-stubs:
    deps:
      - compile:recurring
    cmds:
      - bun openapi-generator-cli generate -c config/server-stubs.yaml
