version: "3"

includes:
  api:
    taskfile: apps/api/Taskfile.yaml
    dir: apps/api/

  web:
    taskfile: apps/web/Taskfile.yaml
    dir: apps/web/

  sheets:
    taskfile: apps/sheets/Taskfile.yaml
    dir: apps/sheets/

  openapi:
    taskfile: packages/openapi/Taskfile.yaml
    dir: packages/openapi/

tasks:
  reindex:
    cmd: uvx code-review-graph build
    sources:
      - "apps/**/*"
      - "ops/**/*"
      - "packages/**/*"

  deps:bun:
    cmd: bun update --latest -i --filter "*"

  oxlint:
    cmd: bun oxlint

  nuke_node_modules:
    cmd: find . -name node_modules -type d -prune -exec rm -rf {} +
