version: "3"

includes:
  openapi:
    taskfile: ../../packages/openapi/Taskfile.yaml
    dir: ../../packages/openapi/

tasks:
  dev:
    deps:
      - openapi:compile:sheets
    cmd: bun --hot src/cmd.ts

  typecheck:
    deps:
      - openapi:compile:sheets
    cmd: bun tsc
