"$schema" = "./node_modules/wrangler/config-schema.json"
name = "recurring-inertia"
compatibility_date = "2026-05-04"
main = "./src/worker.ts"

[vars]
RECURRING_API_ORIGIN = "http://localhost:8080"
GOOGLE_AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_ENDPOINT = "https://openidconnect.googleapis.com/v1/userinfo"

[env.developement]

[env.developement.vars]
RECURRING_API_ORIGIN = "http://localhost:8080"
GOOGLE_AUTHORIZATION_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_ENDPOINT = "https://openidconnect.googleapis.com/v1/userinfo"

[env.test]

[env.test.vars]
RECURRING_API_ORIGIN = "http://localhost:8082"
GOOGLE_AUTHORIZATION_ENDPOINT = "http://localhost:8081/authorize"
GOOGLE_TOKEN_ENDPOINT = "http://localhost:8081/token"
GOOGLE_USERINFO_ENDPOINT = "http://localhost:8081/userinfo"
GOOGLE_CLIENT_ID = "test-google-client"
GOOGLE_CLIENT_SECRET = "test-google-secret"
GOOGLE_REDIRECT_URI = ""
