openapi: 3.1.0
info:
  title: Recurring API
  version: "1"
paths:
  /v1/expenses:
    get:
      operationId: listExpenses
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Expense"
                minItems: 0
    post:
      operationId: createExpense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateExpense"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
components:
  schemas:
    NonEmptyString:
      type: string
      minLength: 1
    unixMillis:
      description: UNIX epoch milliseconds
      type: integer
      format: int64
    MinorUnitAmount:
      description: Monetary value multiplied by 100.
      minimum: 0
      type: integer
      format: int64
    CurrencyCode:
      type: string
      description: ISO 4217 alpha currency code.
      examples:
        - USD
        - EUR
      pattern: "^[A-Z]{3}$"
    Money:
      type: object
      properties:
        amount:
          $ref: "#/components/schemas/MinorUnitAmount"
        currency:
          $ref: "#/components/schemas/CurrencyCode"
      required:
        - amount
        - currency
    RecurringInterval:
      type: string
      examples:
        - P1W
        - P1M
        - P1Y
      description: Subscription billing period length as an RFC 3339 duration.
      format: duration
    httpURL:
      type: string
      format: uri
      pattern: ^https?://\S+$
    Expense:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/NonEmptyString"
        created_at:
          $ref: "#/components/schemas/unixMillis"
          description: db timestamp
        start_at:
          $ref: "#/components/schemas/unixMillis"
          description: when Subscription start
        money:
          $ref: "#/components/schemas/Money"
        recurring:
          $ref: "#/components/schemas/RecurringInterval"
        category:
          $ref: "#/components/schemas/NonEmptyString"
        comment:
          type: string
        canceled_at:
          $ref: "#/components/schemas/unixMillis"
        cancel_url:
          $ref: "#/components/schemas/httpURL"
      required:
        - name
        - created_at
        - start_at
        - money
        - recurring
    CreateExpense:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/NonEmptyString"
        money:
          $ref: "#/components/schemas/Money"
        recurring:
          $ref: "#/components/schemas/RecurringInterval"
        category:
          $ref: "#/components/schemas/NonEmptyString"
        comment:
          type: string
        cancel_url:
          $ref: "#/components/schemas/httpURL"
      required:
        - name
        - money
        - recurring
