version: 3

tasks:
  typecheck:
    run: once
    cmd: bun tsc
    sources:
      - ../../bun.lock
      - package.json
      - tsconfig.json
      - src/**/*

  test:
    run: once
    cmd: bun test
    sources:
      - ../../bun.lock
      - package.json
      - src/**/*

  lint:
    run: once
    dir: ../../
    cmd: bun oxlint --config oxlint.config.ts apps/shared-ts/src/
    sources:
      - bun.lock
      - oxlint.config.ts
      - apps/shared-ts/src/**/*

  check:
    run: once
    deps:
      - lint
      - typecheck
      - test
