// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './worker.ts'

export type PageName = '404' | 'Home' | 'Login' | 'Project' | 'Status'

declare module '@hono/inertia' {
  interface InertiaPages {
    '404': unknown
    'Home': unknown
    'Login': unknown
    'Project': unknown
    'Status': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
