// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './worker.ts'

export type PageName = 'Home' | 'Status'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Home': unknown
    'Status': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
