/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime=false` (hash: 8dcb82fce62138d682a0e1cf55a696fa)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface DevelopementEnv {
		RECURRING_API_ORIGIN: "http://localhost:8080";
		GOOGLE_AUTHORIZATION_ENDPOINT: "https://accounts.google.com/o/oauth2/v2/auth";
		GOOGLE_TOKEN_ENDPOINT: "https://oauth2.googleapis.com/token";
		GOOGLE_USERINFO_ENDPOINT: "https://openidconnect.googleapis.com/v1/userinfo";
	}
	interface TestEnv {
		RECURRING_API_ORIGIN: "http://localhost:8082";
		GOOGLE_AUTHORIZATION_ENDPOINT: "http://localhost:8081/authorize";
		GOOGLE_TOKEN_ENDPOINT: "http://localhost:8081/token";
		GOOGLE_USERINFO_ENDPOINT: "http://localhost:8081/userinfo";
		GOOGLE_CLIENT_ID: "test-google-client";
		GOOGLE_CLIENT_SECRET: "test-google-secret";
		GOOGLE_REDIRECT_URI: "";
	}
	interface Env {
		RECURRING_API_ORIGIN: "http://localhost:8080" | "http://localhost:8082";
		GOOGLE_AUTHORIZATION_ENDPOINT: "https://accounts.google.com/o/oauth2/v2/auth" | "http://localhost:8081/authorize";
		GOOGLE_TOKEN_ENDPOINT: "https://oauth2.googleapis.com/token" | "http://localhost:8081/token";
		GOOGLE_USERINFO_ENDPOINT: "https://openidconnect.googleapis.com/v1/userinfo" | "http://localhost:8081/userinfo";
		GOOGLE_CLIENT_ID?: "test-google-client";
		GOOGLE_CLIENT_SECRET?: "test-google-secret";
		GOOGLE_REDIRECT_URI?: "";
	}
}
interface Env extends Cloudflare.Env {}
