name: recurring

services:
  postgres:
    # latest as of may 2026
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recurring
      POSTGRES_PASSWORD: not-a-secret
      POSTGRES_DB: recurring
    volumes:
      - recurring_pgdata:/var/lib/postgresql

  jaeger:
    image: jaegertracing/jaeger:2.17.0
    # Jaeger runs as UID 10001 by default, but the Badger volume is root-owned.
    user: root
    command:
      - --config
      - /etc/jaeger/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
    volumes:
      - ./jaeger-config.yaml:/etc/jaeger/config.yaml:ro
      - recurring_jaeger_badger:/badger

volumes:
  recurring_pgdata:
  recurring_jaeger_badger:
