name: recurring

services:
  postgres:
    # latest as of may 2026
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recurring
      POSTGRES_PASSWORD: not-a-secret
      POSTGRES_DB: recurring
    volumes:
      - recurring_pgdata:/var/lib/postgresql

volumes:
  recurring_pgdata:
