service:
  extensions:
    - jaeger_storage
    - jaeger_query
    - healthcheckv2
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - jaeger_storage_exporter

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: :13133
  jaeger_query:
    storage:
      traces: local_badger
    grpc:
      endpoint: :16685
    http:
      endpoint: :16686
  jaeger_storage:
    backends:
      local_badger:
        badger:
          directories:
            keys: /badger
            values: /badger
          ephemeral: false
          ttl:
            spans: 48h

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: local_badger
